---
- name: Create AD User
  win_domain_user:
   name: "{{ item.name }}"
   firstname: "{{item.firstname }}"
   surname: "{{ item.surname }}"
   password: "{{ item.password }}"
   state: present
   email: '"{{ item.name }}"@ad1.3e6d.example.opentlc.com'
  with_items: "{{ user_info }}"
